name: white wine quality workflow

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      
      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python preprocessing.py
          python train.py

          echo "# MODEL METRICS" >> report.md
          cat metrics.txt >> report.md
          
          echo "# Confusion Matrix" >> report.md
          cml-publish figures/confustion_matrix_plot.png --md >> report.md
          
          echo "# ROC_Curve" >> report.md
          cml-publish figures/ROC_Curve.png --md >> report.md
          
          echo "# Residuals Plot" >> report.md
          cml-publish figures/Residuals_plot.png --md >> report.md
          
          cml-send-comment report.md

